[pack]
id = "ffmpeg_pack"
name = "FFmpeg Pack"
version = "1.0.0"
api = 1
entry = "pack.py"
dependencies = ["http_pack", "extract_pack"]
schemes = ["gd3+ffmpeg"]
tasks = ["ffmpeg_install", "ffmpeg_merge"]
stages = ["http_download", "extract_archive", "ffmpeg_merge"]
