[project]
name = "ghost-downloader-3"
version = "3.6.1"
description = "A cross-platform QUIC AI-boost fluent-design multi-threaded downloader built with Python."
requires-python = ">=3.10"
dependencies = [
    "PySide6-Fluent-Widgets>=1.8.0",
    "PySideSix-Frameless-Window>=0.7.1",
    "PySide6==6.9.1",
    "loguru",
    "curl-cffi",
    "desktop-notifier",
    "darkdetect[macos-listener]; sys_platform=='darwin'"
]

[project.optional-dependencies]
dev = [
    "nuitka==2.7.11"
]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "app*",
    "view*",
    "plugins*",
    "chrome_extension*",
    "firefox_extension*"
]
exclude = ["tests*"]
