name: 功能需求
description: 提出功能建议
title: "[Feature] "
labels:
  - "✨Enhancement"
body:
- type: checkboxes
  id: no-duplicate
  attributes:
    label: 检查清单
    options:
      - label: 我已搜索现有 Issue 和 Discussions，确认没有重复
        required: true

- type: textarea
  id: problem-description
  attributes:
    label: 问题描述
    description: 你想解决什么问题？当前缺少这个功能给你带来了什么困扰？
  validations:
    required: true

- type: textarea
  id: solution-description
  attributes:
    label: 期望方案
    description: 你期望的解决方式是什么？
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: 备选方案

- type: textarea
  id: additional-info
  attributes:
    label: 补充信息
    render: markdown
