name: Upstream Sync

permissions:
    contents: write

on:
    schedule:
        - cron: "0 0 * * *" # Everyday
    workflow_dispatch:

jobs:
    sync_with_upstream:
        name: Sync with Upstream
        runs-on: ubuntu-latest
        if: ${{ github.event.repository.fork }}

        steps:
            - name: Checkout target repo
              uses: actions/checkout@v3

            - name: Sync upstream changes
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                  upstream_sync_repo: XiaoYouChR/Ghost-Downloader-3
                  upstream_sync_branch: main
                  target_sync_branch: main
                  test_mode: false

            - name: Check for Failure
              if: failure()
              run: |
                  echo "[错误]自动同步失败，请手动同步。"
                  exit 1